
package soap.test.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.6
 * Wed May 17 14:36:17 IST 2023
 * Generated source version: 3.5.6
 */

@XmlRootElement(name = "storeMarksResponse", namespace = "http://test.soap/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "storeMarksResponse", namespace = "http://test.soap/")

public class StoreMarksResponse {


}

